# ================================
# CONFIGURATION IRONFORGE
# ================================

# Nom de l'application
spring.application.name=ironforge

# ================================
# BASE DE DONNÉES MySQL
# ================================
spring.datasource.url=jdbc:mysql://localhost:3306/ironforge?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:janvier2004}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ================================
# JPA / HIBERNATE
# ================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

stripe.secret.key=${STRIPE_SECRET_KEY}
stripe.public.key=${STRIPE_PUBLIC_KEY}
# ================================
# JWT SECURITY
# ================================
jwt.secret=jwt.secret=aXJvbmZvcmdlU2VjcmV0S2V5MjAyNklyb25Gb3JnZVNlY3VyaXR5S2V5
jwt.expiration=86400000


# ================================
# SERVEUR
# ================================
server.port=${PORT:8085}

# ================================
# LOGS
# ================================
logging.level.com.ironforge=DEBUG
logging.level.org.springframework.security=DEBUG
